name: Actualizar Canales TV

on:
  schedule:
    - cron: '*/30 * * * *' # Ejecutar cada 30 min
  workflow_dispatch: # BotÃ³n manual

jobs:
  build:
    runs-on: ubuntu-latest
    
    # ðŸ‘‡ ESTO ES LO QUE FALTABA PARA QUE PUEDA GUARDAR EL ARCHIVO
    permissions:
      contents: write

    steps:
      - name: Bajar cÃ³digo
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar librerÃ­as
        run: pip install requests

      - name: Correr el Scraper
        run: python scraper.py

      - name: Guardar cambios (Commit & Push)
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Actualizacion Automatica de Links
          file_pattern: channels.json canales.json # Por las dudas puse los dos nombres
          branch: main
